server:
  port: 8080
  servlet:
    context-path: /api/v1/
  compression: # contents 압축 설정
    enabled: true
    mime-types: text/html,text/plain,text/css,application/javascript,application/json
    min-response-size: 2048

  tomcat:
    connection-timeout: 300000 # 5분
spring:
  application:
    name: setak-fire-backend
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL57Dialect
    generate-ddl: true
    properties:
      hibernate:
        ddl-auto: create
        jdbc:
          batch_size: 10
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: ENC(RTl/RVmJUTUU/zrAOzzInVK0cvMkPVKZXWF8C0IUhraLcw7EvurKNIOfmb6HrhOOyUdsPwGQJ2QOZ3NTSsdjV26eG7695Spv)
    username: ENC(PZFRpoJoaIqLe6o30AfiLNVmRxvtQN8IyeaaY1XuDC4=)
    password: ENC(nwqc82whU9x+PWAabe0uM9IwR+WVqylFfMgUzm52pSM=)
    dbcp2:
      default-schema: setakfire
  jackson:
    time-zone: Asia/Seoul
jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    bean: jasyptStringEncryptor
    pool-size: 1
    string-output-type: base64
    key-obtention-iterations: 1000
jwt:
  secret-key: ENC(tQPe08SWlh6mbiaK+wLpO1sDyLGdLUXCP3Sjp/H/5nfxEHdrcRSG3w==)

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger
    operations-sorter: alpha
    tags-sorter: alpha
    disable-swagger-default-url: true
    display-request-duration: true
    filter: true # 태그 검색필터
  default-consumes-media-type: application/json
  default-produces-media-type: application/json