server:
  port: 8080
  servlet:
    context-path: /api/v1/
spring:
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: true
        globally_quoted_identifiers_skip_column_definitions: true