server:
  port: 8080
  servlet:
    context-path: /api/v1/
  compression: # contents 압축 설정
    enabled: true
    mime-types: text/html,text/plain,text/css,application/javascript,application/json
    min-response-size: 2048

  tomcat:
    connection-timeout: 300000 # 5분
spring:
  application:
    name: setak-fire-backend
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL57Dialect
    generate-ddl: true
    properties:
      hibernate:
        ddl-auto: create
        jdbc:
          batch_size: 10
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://localhost:3306/setakfire
    username: root
    password: 1234
#    username: ENC(VLE2M0yVHkt5TxyJBKEvXTEFFUrmPPc4TMH/p5EojtE=)
#    password: ENC(mxqGDr+un20sPaYg4zqER9hi5vf87I75z0g/1Az1rt4=)
    dbcp2:
      default-schema: setakfire
  jackson:
    time-zone: Asia/Seoul
jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    bean: jasyptStringEncryptor
    pool-size: 1
    string-output-type: base64
    key-obtention-iterations: 1000
springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger
    operations-sorter: alpha
    tags-sorter: alpha
    disable-swagger-default-url: true
    display-request-duration: true
    filter: true # 태그 검색필터
  default-consumes-media-type: application/json
  default-produces-media-type: application/json